plugins {
    id 'java'
}

group = 'philv.ru'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation ('org.junit.jupiter:junit-jupiter:5.10.2',
            'com.codeborne:selenide:7.3.1',
            'com.github.javafaker:javafaker:1.0.2')
}

test {
    useJUnitPlatform()
}